# Application Settings
app:
  name: "Personalized News Briefing Chatbot"
  version: "1.0.0"
  debug: false
  host: "0.0.0.0"
  port: 8000

# Model Configuration
models:
  summarization:
    model_name: "google/pegasus-newsroom"
    max_length: 150
    min_length: 50
    num_beams: 4
    early_stopping: true
    
  qa:
    model_name: "deepset/roberta-base-squad2"
    max_answer_length: 100
    confidence_threshold: 0.5
    max_context_length: 512
    
  embeddings:
    model_name: "all-MiniLM-L6-v2"
    dimension: 384
    batch_size: 32

# Pinecone Configuration
pinecone:
  index_name: "news-embeddings"
  dimension: 384
  metric: "cosine"
  pods: 1
  pod_type: "p1.x1"

# RSS Configuration
rss:
  feeds:
    - "https://feeds.reuters.com/reuters/topNews"
    - "https://rss.cnn.com/rss/edition.rss"
    - "https://feeds.bbci.co.uk/news/world/rss.xml"
    - "https://feeds.npr.org/1001/rss.xml"
  update_interval: 300  # seconds
  max_articles_per_feed: 50

# Performance Settings
performance:
  max_workers: 4
  batch_size: 8
  cache_ttl: 3600
  request_timeout: 30
  max_concurrent_requests: 100

# Search Settings
search:
  default_limit: 10
  max_limit: 50
  similarity_threshold: 0.7
